### ISSUE TITLE
Leverage existing password strength to bioemtric FMR models

### ISSUE THREAD

**Issue by taprootsec** [usnistgov/SOFA#5]
**Organization**: Taproot Security

**Type**: 2

**Reference (Include section and paragraph number)**: 

**Comment (Include rationale for comment)**: I applaud NIST's ambitious effort to unify biometric and non-biometric authentication strength measures.  Past work has been published that explores a possible framework to translate password strength to biometric FMR tolerances, with the intent of helping biometric authentication implementers calibrate false match thresholds based on their legacy password strength policies.  I call your attention specifically to my article "Optimizing False Match Rate in Biometric System Deployments” in ISSA Journal, December 2009.

**Suggested Change**: Incorporate password-to-biometric conversion models in SOFA so that organizations who have established password strength policies can adapt them to biometric authentication systems.  For example, SOFA should help an organization calibrate FMR of a fingerprint system to achieve equivalence to a previous system that relied on 4-digit PINs.

```


```

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by rajdinh** [comment]
Thank you for your comment! SOFA is ultimately meant to examine and compare the strength of different authentication mechanisms. We are looking into how to quantify (if possible) different configurations and combinations of technologies so that the equivalence that you mentioned is clearer (i.e., getting SOFA-B, for biometrics, and being able to compare it to password/pin strength, or calculating the strength of using both). Once SOFA-B is better established, we will look to expand this work out to other authentication systems. In the end, SOFA hopes to better inform organizational decisions, specifically around the type of authenticators used for specific applications and transactions. 

We also appreciate the reference to your article. We intend to build upon existing studies and efforts as much as possible, and welcome any references to past work that people believe could help shape SOFA.

-SOFA Team
